### ISSUE TITLE
fyne-cross fails with invalid USER mode in GitHub Actions

### ISSUE THREAD

**Issue by alexrudd** [fyne-io/fyne-cross#100]
### Describe the bug:

When running a fyne-cross build in a GitHub Actions workflow, I get the error:

```
docker: --userns: invalid USER mode.
See 'docker run --help'.
[✗] could not package the Fyne app: exit status 125
```

### To Reproduce:

Create a GitHub Actions workflow with the following yaml:

```yaml
name: Bug Repro
on:
  pull_request:
  push:

jobs:
  build:
    name: Build Calculator using fyne-cross ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["v1.2.0", "v1.1.3", "v1.1.2", "v1.1.1", "v1.1.0", "v1.0.0"]

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: Install fyne-cross
        run: |
          go install github.com/fyne-io/fyne-cross@${{ matrix.version }}
        env:
          GOBIN: "/usr/local/bin/"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: fyne-io/calculator

      - name: Build
        run: fyne-cross windows --debug --no-cache -name calculator.exe
```

Run the workflow and see it only fails for the latest version 1.2.0

### Example code:

Example workflow: https://github.com/alexrudd/fyne-cross-bug-repro/blob/master/.github/workflows/bugrepro.yml
Example actions output: https://github.com/alexrudd/fyne-cross-bug-repro/actions/runs/2097480389

### Device and debug info (please complete the following information):

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

<summary>Device info</summary>

 - **OS:** Ubuntu
 - **Version:** 20.04
 - **Go version:** 1.18
 - **fyne-cross version:** v1.2.0
 - **Fyne version:** v2.1.4

<details><summary>Debug info</summary><br><pre>
[i] Target: windows/amd64
command.Context{Volume:volume.Volume{binDirHost:"/home/runner/work/fyne-cross-bug-repro/fyne-cross-bug-repro/fyne-cross/bin", cacheDirHost:"/home/runner/.cache/fyne-cross", distDirHost:"/home/runner/work/fyne-cross-bug-repro/fyne-cross-bug-repro/fyne-cross/dist", tmpDirHost:"/home/runner/work/fyne-cross-bug-repro/fyne-cross-bug-repro/fyne-cross/tmp", workDirHost:"/home/runner/work/fyne-cross-bug-repro/fyne-cross-bug-repro"}, Architecture:"amd64", Env:[]string{"GOOS=windows", "GOARCH=amd64", "CC=x[8](https://github.com/alexrudd/fyne-cross-bug-repro/runs/5837367406?check_suite_focus=true#step:5:8)6_64-w64-mingw32-gcc"}, ID:"windows-amd64", LdFlags:[]string{"-H=windowsgui"}, OS:"windows", Tags:[]string(nil), AppBuild:"1", AppID:"", AppVersion:"1.0", CacheEnabled:false, DockerImage:"docker.io/fyneio/fyne-cross:1.2-windows", Icon:"/home/runner/work/fyne-cross-bug-repro/fyne-cross-bug-repro/Icon.png", Name:"calculator.exe", Package:".", Release:false, StripDebug:true, Debug:true, Pull:false, Category:"", Certificate:"", Developer:"", Keystore:"", KeystorePass:"", KeyPass:"", Password:"", Profile:""}
[i] Cleaning target directories...
[✓] "bin" dir cleaned: /home/runner/work/fyne-cross-bug-repro/fyne-cross-bug-repro/fyne-cross/bin/windows-amd64
[✓] "dist" dir cleaned: /home/runner/work/fyne-cross-bug-repro/fyne-cross-bug-repro/fyne-cross/dist/windows-amd64
[✓] "temp" dir cleaned: /home/runner/work/fyne-cross-bug-repro/fyne-cross-bug-repro/fyne-cross/tmp/windows-amd64
[i] Checking for go.mod: /home/runner/work/fyne-cross-bug-repro/fyne-cross-bug-repro/go.mod
[✓] go.mod found
/usr/bin/docker run --rm -t -w /app/fyne-cross/tmp/windows-amd64 -v /home/runner/work/fyne-cross-bug-repro/fyne-cross-bug-repro:/app:z --userns keep-id -e use_podman=1 -e CGO_ENABLED=1 -e GOCACHE=/go/go-build docker.io/fyneio/fyne-cross:1.2-windows /usr/local/bin/gowindres -arch amd64 -output calculator.exe -workdir /app/fyne-cross/tmp/windows-amd64
docker: --userns: invalid USER mode.
See 'docker run --help'.
[✗] could not package the Fyne app: exit status [12](https://github.com/alexrudd/fyne-cross-bug-repro/runs/5837367406?check_suite_focus=true#step:5:12)5
Error: Process completed with exit code 1.
</pre></details>
